Empfänger = input("Name des Empfängers ")
Absender = input("Name des Absenders ")

print(f"Hallo {Empfänger}")
print()
print("Mit dieser E-Mail möchte ichd ich über meine neue Adresse informieren.")
print()
print("Ludwig-Windhorst-Str. 50")
print("76187 Karlsruhe")
print()
print("Viele Grüße")
print(f"{Absender}")